### ISSUE TITLE
Investopedia appears to not use UI4 cookie anymore

### ISSUE THREAD

**Issue by loluwot** [dchrostowski/investopedia_simulator_api#21]
I can no longer find the UI4 session cookie after logging in. Session instead appears to be dictated by PHPSESSID.

**Comment by dchrostowski** [comment]
You're right.  Will try to get a fix in ASAP

**Comment by sachaker** [comment]
Would be amazing—such a useful repo if it works! Thanks for building

**Comment by Ocean-Moist** [comment]
can you please update this please

**Comment by dchrostowski** [comment]
I'll try to get it working this weekend.

**Comment by AndyyTaylor** [comment]
find & replace fixed the issue for me

**Comment by dchrostowski** [comment]
I'll have a fix up sometime tonight, sorry it took so long.  This was difficult to fix.  Will now have a json file with a username and password instead of a cookie.

**Comment by Ocean-Moist** [comment]
I’m using Alpaca for my stock sims but good job.

**Comment by JplepeckiBR** [comment]
# Current Status?
### Hello guys, hope everyone is doing well 😀👍
Does anybody have an idea of how the authentication is currently working in this library?
I am not able to login via credentials, since the current login process seems to envolve 2FA via a email code.

Was aiming to programmatically trade in [Investopedia´s simmulation](https://www.investopedia.com/simulator) for a Uni class, if everyone knows the current "way around" the current situation, please let me know at **group3finmarket@gmail.com**.


## Summary: 
### No more Passwords❌
### 2 Factor Authentication (Gmail Code)✅
